# Generated by Django 3.1.1 on 2020-09-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=20)),
                ('p_name', models.CharField(max_length=20)),
                ('p_image', models.ImageField(upload_to='images/')),
                ('p_price', models.IntegerField(default=0)),
                ('p_sold_out', models.BooleanField(default=False)),
            ],
        ),
    ]
