# Generated by Django 3.1.1 on 2020-10-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='region',
        ),
    ]
