# Generated by Django 3.1.1 on 2020-09-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_info',
            field=models.TextField(default='상품 상세정보'),
        ),
    ]
