# Generated by Django 3.1.1 on 2020-09-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectApp', '0002_products_p_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_info',
            field=models.TextField(),
        ),
    ]
