# Generated by Django 3.1.1 on 2020-09-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectApp', '0003_auto_20200927_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='region',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
