# Generated by Django 3.1.1 on 2020-09-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectApp', '0004_products_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='region',
            field=models.CharField(max_length=20),
        ),
    ]
