# Generated by Django 3.1.1 on 2020-09-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selectApp', '0005_auto_20200928_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('storeName', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='region',
        ),
        migrations.AlterField(
            model_name='products',
            name='storeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectApp.region'),
        ),
    ]
