# Generated by Django 3.1.1 on 2020-09-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectApp', '0006_auto_20200928_0402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
