# Generated by Django 2.1.5 on 2020-10-04 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('store_name', models.CharField(max_length=50, null=True)),
                ('date_time', models.CharField(max_length=50, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.AddField(
            model_name='apply',
            name='newProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newProduct.NewProduct'),
        ),
    ]
