# Generated by Django 3.1.1 on 2020-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0003_auto_20200927_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
